apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: default # Use the Jenkins namespace you created (if applicable)
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
